version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db:rw
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat_user_root
      MONGO_INITDB_ROOT_PASSWORD: chat_passwd_root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chat_user_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: chat_passwd_root
      ME_CONFIG_MONGODB_URL: mongodb://chat_user_root:chat_passwd_root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
